// s.o.c.i.a.r.i.u.m
// HASHIMOTO, Yasuhiro (E-mail: hy @ sys.t.u-tokyo.ac.jp)
// update: 2009/05/10

/* Copyright (c) 2005-2009, HASHIMOTO, Yasuhiro, All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *   - Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *
 *   - Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *
 *   - Neither the name of the University of Tokyo nor the names of its contributors
 *     may be used to endorse or promote products derived from this software without
 *     specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H
#define INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H

#ifdef _MSC_VER
#include <windows.h>
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////
// タイマー
#define ID_TIMER_DRAW	0
#define ID_TIMER_SELECT	1
#define ID_TIMER_ZOOM	2
#define ID_TIMER_FORCE_DIRECTION	3

////////////////////////////////////////////////////////////////////////////////////////////////////
// メニュー

#define	IDM_HELP	0

// キーボード
#define	IDM_KEY_ENTER	1
#define	IDM_KEY_ESCAPE	2
#define	IDM_KEY_SPACE	3
#define	IDM_KEY_HOME	4
#define	IDM_KEY_END	5
#define IDM_KEY_INSERT	6
#define IDM_KEY_DELETE	7
#define	IDM_KEY_NEXT	8
#define	IDM_KEY_PRIOR	9

#define	IDM_KEY_UP	10
#define	IDM_KEY_DOWN	11
#define	IDM_KEY_RIGHT	12
#define	IDM_KEY_LEFT	13

#define	IDM_KEY_CTRL_UP	50
#define	IDM_KEY_CTRL_DOWN	51
#define	IDM_KEY_CTRL_RIGHT	52
#define	IDM_KEY_CTRL_LEFT	53

#define	IDM_KEY_CTRL_SPACE	63
#define	IDM_KEY_CTRL_HOME	64
#define	IDM_KEY_CTRL_DELETE	67

#define	IDM_KEY_1	100
#define	IDM_KEY_2	101
#define	IDM_KEY_3	102
#define	IDM_KEY_4	103
#define	IDM_KEY_5	104
#define	IDM_KEY_6	105
#define	IDM_KEY_7	106
#define	IDM_KEY_8	107
#define	IDM_KEY_9	108
#define	IDM_KEY_0	109

#define	IDM_KEY_SHIFT_1	110
#define	IDM_KEY_SHIFT_2	111
#define	IDM_KEY_SHIFT_3	112
#define	IDM_KEY_SHIFT_4	113
#define	IDM_KEY_SHIFT_5	114
#define	IDM_KEY_SHIFT_6	115
#define	IDM_KEY_SHIFT_7	116
#define	IDM_KEY_SHIFT_8	117
#define	IDM_KEY_SHIFT_9	118
#define	IDM_KEY_SHIFT_0	119

#define	IDM_KEY_CTRL_1	120
#define	IDM_KEY_CTRL_2	121
#define	IDM_KEY_CTRL_3	122
#define	IDM_KEY_CTRL_4	123
#define	IDM_KEY_CTRL_5	124
#define	IDM_KEY_CTRL_6	125
#define	IDM_KEY_CTRL_7	126
#define	IDM_KEY_CTRL_8	127
#define	IDM_KEY_CTRL_9	128
#define	IDM_KEY_CTRL_0	129

#define	IDM_KEY_SHIFT_CTRL_1	130
#define	IDM_KEY_SHIFT_CTRL_2	131
#define	IDM_KEY_SHIFT_CTRL_3	132
#define	IDM_KEY_SHIFT_CTRL_4	133
#define	IDM_KEY_SHIFT_CTRL_5	134
#define	IDM_KEY_SHIFT_CTRL_6	135
#define	IDM_KEY_SHIFT_CTRL_7	136
#define	IDM_KEY_SHIFT_CTRL_8	137
#define	IDM_KEY_SHIFT_CTRL_9	138
#define	IDM_KEY_SHIFT_CTRL_0	139

#define	IDM_KEY_A	140
#define	IDM_KEY_B	141
#define	IDM_KEY_C	142
#define	IDM_KEY_D	143
#define	IDM_KEY_E	144
#define	IDM_KEY_F	145
#define	IDM_KEY_G	146
#define	IDM_KEY_H	147
#define	IDM_KEY_I	148
#define	IDM_KEY_J	149
#define	IDM_KEY_K	150
#define	IDM_KEY_L	151
#define	IDM_KEY_M	152
#define	IDM_KEY_N	153
#define	IDM_KEY_O	154
#define	IDM_KEY_P	155
#define	IDM_KEY_Q	156
#define	IDM_KEY_R	157
#define	IDM_KEY_S	158
#define	IDM_KEY_T	159
#define	IDM_KEY_U	160
#define	IDM_KEY_V	161
#define	IDM_KEY_W	162
#define	IDM_KEY_X	163
#define	IDM_KEY_Y	164
#define	IDM_KEY_Z	165

#define	IDM_KEY_CTRL_A	166
#define	IDM_KEY_CTRL_B	167
#define	IDM_KEY_CTRL_C	168
#define	IDM_KEY_CTRL_D	169
#define	IDM_KEY_CTRL_E	170
#define	IDM_KEY_CTRL_F	171
#define	IDM_KEY_CTRL_G	172
#define	IDM_KEY_CTRL_H	173
#define	IDM_KEY_CTRL_I	174
#define	IDM_KEY_CTRL_J	175
#define	IDM_KEY_CTRL_K	176
#define	IDM_KEY_CTRL_L	177
#define	IDM_KEY_CTRL_M	178
#define	IDM_KEY_CTRL_N	179
#define	IDM_KEY_CTRL_O	180
#define	IDM_KEY_CTRL_P	181
#define	IDM_KEY_CTRL_Q	182
#define	IDM_KEY_CTRL_R	183
#define	IDM_KEY_CTRL_S	184
#define	IDM_KEY_CTRL_T	185
#define	IDM_KEY_CTRL_U	186
#define	IDM_KEY_CTRL_V	187
#define	IDM_KEY_CTRL_W	188
#define	IDM_KEY_CTRL_X	189
#define	IDM_KEY_CTRL_Y	190
#define	IDM_KEY_CTRL_Z	191

#define	IDM_KEY_SHIFT_A	192
#define	IDM_KEY_SHIFT_B	193
#define	IDM_KEY_SHIFT_C	194
#define	IDM_KEY_SHIFT_D	195
#define	IDM_KEY_SHIFT_E	196
#define	IDM_KEY_SHIFT_F	197
#define	IDM_KEY_SHIFT_G	198
#define	IDM_KEY_SHIFT_H	199
#define	IDM_KEY_SHIFT_I	200
#define	IDM_KEY_SHIFT_J	201
#define	IDM_KEY_SHIFT_K	202
#define	IDM_KEY_SHIFT_L	203
#define	IDM_KEY_SHIFT_M	204
#define	IDM_KEY_SHIFT_N	205
#define	IDM_KEY_SHIFT_O	206
#define	IDM_KEY_SHIFT_P	207
#define	IDM_KEY_SHIFT_Q	208
#define	IDM_KEY_SHIFT_R	209
#define	IDM_KEY_SHIFT_S	210
#define	IDM_KEY_SHIFT_T	211
#define	IDM_KEY_SHIFT_U	212
#define	IDM_KEY_SHIFT_V	213
#define	IDM_KEY_SHIFT_W	214
#define	IDM_KEY_SHIFT_X	215
#define	IDM_KEY_SHIFT_Y	216
#define	IDM_KEY_SHIFT_Z	217

#define	IDM_KEY_SHIFT_CTRL_A	218
#define	IDM_KEY_SHIFT_CTRL_B	219
#define	IDM_KEY_SHIFT_CTRL_C	220
#define	IDM_KEY_SHIFT_CTRL_D	221
#define	IDM_KEY_SHIFT_CTRL_E	222
#define	IDM_KEY_SHIFT_CTRL_F	223
#define	IDM_KEY_SHIFT_CTRL_G	224
#define	IDM_KEY_SHIFT_CTRL_H	225
#define	IDM_KEY_SHIFT_CTRL_I	226
#define	IDM_KEY_SHIFT_CTRL_J	227
#define	IDM_KEY_SHIFT_CTRL_K	228
#define	IDM_KEY_SHIFT_CTRL_L	229
#define	IDM_KEY_SHIFT_CTRL_M	230
#define	IDM_KEY_SHIFT_CTRL_N	231
#define	IDM_KEY_SHIFT_CTRL_O	232
#define	IDM_KEY_SHIFT_CTRL_P	233
#define	IDM_KEY_SHIFT_CTRL_Q	234
#define	IDM_KEY_SHIFT_CTRL_R	235
#define	IDM_KEY_SHIFT_CTRL_S	236
#define	IDM_KEY_SHIFT_CTRL_T	237
#define	IDM_KEY_SHIFT_CTRL_U	238
#define	IDM_KEY_SHIFT_CTRL_V	239
#define	IDM_KEY_SHIFT_CTRL_W	240
#define	IDM_KEY_SHIFT_CTRL_X	241
#define	IDM_KEY_SHIFT_CTRL_Y	242
#define	IDM_KEY_SHIFT_CTRL_Z	243

// EDIT
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_EDGES	300
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_EDGES_ALL	301
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_ELEMENTS	302
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_ELEMENTS_ALL	303
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_NODES	304
#define	IDM_EDIT_FOR_ALL_HIDE_MARKED_NODES_ALL	305
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_EDGES	306
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_EDGES_ALL	307
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_ELEMENTS	308
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_ELEMENTS_ALL	309
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_NODES	310
#define	IDM_EDIT_FOR_ALL_REMOVE_MARKED_NODES_ALL	311
#define	IDM_EDIT_FOR_ALL_SELECT_ALL	312
#define	IDM_EDIT_FOR_ALL_SELECT_COMMUNITIES	313
#define	IDM_EDIT_FOR_ALL_SELECT_COMMUNITY_EDGES	314
#define	IDM_EDIT_FOR_ALL_SELECT_EDGES	315
#define	IDM_EDIT_FOR_ALL_SELECT_INNER_COMMUNITY_EDGES	316
#define	IDM_EDIT_FOR_ALL_SELECT_INNER_COMMUNITY_NODES	317
#define	IDM_EDIT_FOR_ALL_SELECT_INNER_COMMUNITY_ELEMENTS	318
#define	IDM_EDIT_FOR_ALL_SELECT_INVERT	319
#define	IDM_EDIT_FOR_ALL_SELECT_NODES	320
#define	IDM_EDIT_FOR_ALL_SELECT_OUTER_COMMUNITY_EDGES	321
#define	IDM_EDIT_FOR_ALL_SELECT_OUTER_COMMUNITY_NODES	322
#define	IDM_EDIT_FOR_ALL_SELECT_OUTER_COMMUNITY_ELEMENTS	323
#define	IDM_EDIT_FOR_ALL_SHOW_EDGES	324
#define	IDM_EDIT_FOR_ALL_SHOW_ELEMENTS	325
#define	IDM_EDIT_FOR_ALL_SHOW_NODES	326
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_EDGES	327
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_EDGES_ALL	328
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_ELEMENTS	329
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_ELEMENTS_ALL	330
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_NODES	331
#define	IDM_EDIT_FOR_CURRENT_HIDE_MARKED_NODES_ALL	332
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_EDGES	333
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_EDGES_ALL	334
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_ELEMENTS	335
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_ELEMENTS_ALL	336
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_NODES	337
#define	IDM_EDIT_FOR_CURRENT_REMOVE_MARKED_NODES_ALL	338
#define	IDM_EDIT_FOR_CURRENT_SELECT_ALL	339
#define	IDM_EDIT_FOR_CURRENT_SELECT_COMMUNITIES	340
#define	IDM_EDIT_FOR_CURRENT_SELECT_COMMUNITY_EDGES	341
#define	IDM_EDIT_FOR_CURRENT_SELECT_EDGES	342
#define	IDM_EDIT_FOR_CURRENT_SELECT_INNER_COMMUNITY_EDGES	343
#define	IDM_EDIT_FOR_CURRENT_SELECT_INNER_COMMUNITY_NODES	344
#define	IDM_EDIT_FOR_CURRENT_SELECT_INNER_COMMUNITY_ELEMENTS	345
#define	IDM_EDIT_FOR_CURRENT_SELECT_INVERT	346
#define	IDM_EDIT_FOR_CURRENT_SELECT_NODES	347
#define	IDM_EDIT_FOR_CURRENT_SELECT_OUTER_COMMUNITY_EDGES	348
#define	IDM_EDIT_FOR_CURRENT_SELECT_OUTER_COMMUNITY_NODES	349
#define	IDM_EDIT_FOR_CURRENT_SELECT_OUTER_COMMUNITY_ELEMENTS	350
#define	IDM_EDIT_FOR_CURRENT_SHOW_EDGES	351
#define	IDM_EDIT_FOR_CURRENT_SHOW_ELEMENTS	352
#define	IDM_EDIT_FOR_CURRENT_SHOW_NODES	353

// LAYOUT
#define	IDM_LAYOUT_EXECUTE	360
#define	IDM_LAYOUT_KAMADA_KAWAI_METHOD	361
#define	IDM_LAYOUT_HIGH_DIMENSIONAL_EMBEDDING	362
#define	IDM_LAYOUT_CIRCLE	363
#define	IDM_LAYOUT_CIRCLE_IN_SIZE_ORDER	364
#define	IDM_LAYOUT_ARRAY	365
#define	IDM_LAYOUT_RANDOM	366
#define	IDM_LAYOUT_FORCE_DIRECTION	367
#define IDM_LAYOUT_AUTO	368

// FONT_SIZE
#define	IDM_FONT_SIZE_NODE_0	370
#define	IDM_FONT_SIZE_NODE_1	371
#define	IDM_FONT_SIZE_NODE_2	372
#define	IDM_FONT_SIZE_NODE_3	373
#define	IDM_FONT_SIZE_EDGE_0	374
#define	IDM_FONT_SIZE_EDGE_1	375
#define	IDM_FONT_SIZE_EDGE_2	376
#define	IDM_FONT_SIZE_EDGE_3	377
#define	IDM_FONT_SIZE_COMMUNITY_0	378
#define	IDM_FONT_SIZE_COMMUNITY_1	379
#define	IDM_FONT_SIZE_COMMUNITY_2	380
#define	IDM_FONT_SIZE_COMMUNITY_3	381
#define	IDM_FONT_SIZE_COMMUNITY_EDGE_0	382
#define	IDM_FONT_SIZE_COMMUNITY_EDGE_1	383
#define	IDM_FONT_SIZE_COMMUNITY_EDGE_2	384
#define	IDM_FONT_SIZE_COMMUNITY_EDGE_3	385

// VIEW
#define	IDM_SHOW_NODE	390
#define	IDM_SHOW_EDGE	391
#define	IDM_SHOW_COMMUNITY	392
#define	IDM_SHOW_COMMUNITY_EDGE	393
#define	IDM_SHOW_NODE_LABEL	394
#define	IDM_SHOW_EDGE_LABEL	395
#define	IDM_SHOW_COMMUNITY_LABEL	396
#define	IDM_SHOW_COMMUNITY_EDGE_LABEL	397
#define	IDM_NODE_STYLE_POLYGON	398
#define	IDM_NODE_STYLE_TEXTURE	399
#define	IDM_EDGE_STYLE_STRAIGHT	400
#define	IDM_EDGE_STYLE_HCURVE	401
#define	IDM_EDGE_STYLE_VCURVE	402
#define	IDM_EDGE_STYLE_LINE	403
#define	IDM_EDGE_STYLE_TEXTURE	404
#define	IDM_COMMUNITY_STYLE_POLYGON_CIRCLE	405
#define	IDM_COMMUNITY_STYLE_POLYGON_CURVE	406
#define	IDM_COMMUNITY_STYLE_TEXTURE	407
#define	IDM_COMMUNITY_EDGE_STYLE_STRAIGHT	408
#define	IDM_COMMUNITY_EDGE_STYLE_HCURVE	409
#define	IDM_COMMUNITY_EDGE_STYLE_VCURVE	410
#define	IDM_COMMUNITY_EDGE_STYLE_LINE	411
#define	IDM_COMMUNITY_EDGE_STYLE_TEXTURE	412
#define	IDM_NODE_SIZE_NONE	413
#define	IDM_NODE_SIZE_UNIFORM	414
#define	IDM_NODE_SIZE_REPRESENTS_DEGREE_CENTRALITY	415
#define	IDM_NODE_SIZE_REPRESENTS_CLOSENESS_CENTRALITY	416
#define	IDM_NODE_SIZE_REPRESENTS_BETWEENNESS_CENTRALITY	417
#define	IDM_NODE_SIZE_REPRESENTS_PAGERANK	418
#define	IDM_SHOW_SLIDER	419
#define	IDM_SHOW_TIME_LABEL	420
#define	IDM_SHOW_GRID	421
#define	IDM_SHOW_FPS	422
#define	IDM_SHOW_CENTER	423
#define	IDM_SHOW_LAYOUT_FRAME	424

// COMMUNITY_DETECTION
#define	IDM_COMMUNITY_DETECTION_EXECUTE	430
#define	IDM_CONNECTED_COMPONENTS	431
#define	IDM_STRONGLY_CONNECTED_COMPONENTS	432
#define	IDM_CLIQUE_PERCOLATION_3	433
#define	IDM_CLIQUE_PERCOLATION_4	434
#define	IDM_CLIQUE_PERCOLATION_5	435
#define	IDM_MODULARITY_MAXIMIZATION_USING_GREEDY_METHOD	436
#define	IDM_MODULARITY_MAXIMIZATION_USING_TEO_METHOD	437
#define	IDM_BETWEENNESS_CENTRALITY_CLUSTERING	438
#define	IDM_COMMUNITY_DETECTION_CLEAR	439
#define	IDM_USE_WEIGHTED_MODULARITY	440

#endif // INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H
