// s.o.c.i.a.r.i.u.m: resource.h
// HASHIMOTO, Yasuhiro (E-mail: hy @ sys.t.u-tokyo.ac.jp)

/* Copyright (c) 2005-2009, HASHIMOTO, Yasuhiro, All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *   - Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   - Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in the
 *     documentation and/or other materials provided with the distribution.
 *   - Neither the name of the University of Tokyo nor the names of its
 *     contributors may be used to endorse or promote products derived from
 *     this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
 * TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H
#define INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H

#include <windows.h>

////////////////////////////////////////////////////////////////////////////////
// TIMER

#define ID_TIMER_DRAW	0
#define ID_TIMER_SELECT	1
#define ID_TIMER_ZOOM	2
#define ID_TIMER_AUTO_RUN	3

////////////////////////////////////////////////////////////////////////////////
// MENU

#define	IDM_HELP	0

#define	IDM_KEY_ENTER	10
#define	IDM_KEY_ESCAPE	11
#define	IDM_KEY_SPACE	12
#define	IDM_KEY_HOME	13
#define	IDM_KEY_END	14
#define	IDM_KEY_INSERT	15
#define	IDM_KEY_DELETE	16
#define	IDM_KEY_NEXT	17
#define	IDM_KEY_PRIOR	18
#define	IDM_KEY_UP	19
#define	IDM_KEY_DOWN	20
#define	IDM_KEY_RIGHT	21
#define	IDM_KEY_LEFT	22
#define	IDM_KEY_CTRL_SPACE	23
#define	IDM_KEY_CTRL_HOME	24
#define	IDM_KEY_CTRL_END	25
#define	IDM_KEY_CTRL_INSERT	26
#define	IDM_KEY_CTRL_DELETE	27
#define	IDM_KEY_CTRL_NEXT	28
#define	IDM_KEY_CTRL_PRIOR	29
#define	IDM_KEY_CTRL_UP	30
#define	IDM_KEY_CTRL_DOWN	31
#define	IDM_KEY_CTRL_RIGHT	32
#define	IDM_KEY_CTRL_LEFT	33

#define	IDM_KEY_1	40
#define	IDM_KEY_2	41
#define	IDM_KEY_3	42
#define	IDM_KEY_4	43
#define	IDM_KEY_5	44
#define	IDM_KEY_6	45
#define	IDM_KEY_7	46
#define	IDM_KEY_8	47
#define	IDM_KEY_9	48
#define	IDM_KEY_0	49
#define	IDM_KEY_SHIFT_1	50
#define	IDM_KEY_SHIFT_2	51
#define	IDM_KEY_SHIFT_3	52
#define	IDM_KEY_SHIFT_4	53
#define	IDM_KEY_SHIFT_5	54
#define	IDM_KEY_SHIFT_6	55
#define	IDM_KEY_SHIFT_7	56
#define	IDM_KEY_SHIFT_8	57
#define	IDM_KEY_SHIFT_9	58
#define	IDM_KEY_SHIFT_0	59
#define	IDM_KEY_CTRL_1	60
#define	IDM_KEY_CTRL_2	61
#define	IDM_KEY_CTRL_3	62
#define	IDM_KEY_CTRL_4	63
#define	IDM_KEY_CTRL_5	64
#define	IDM_KEY_CTRL_6	65
#define	IDM_KEY_CTRL_7	66
#define	IDM_KEY_CTRL_8	67
#define	IDM_KEY_CTRL_9	68
#define	IDM_KEY_CTRL_0	69
#define	IDM_KEY_SHIFT_CTRL_1	70
#define	IDM_KEY_SHIFT_CTRL_2	71
#define	IDM_KEY_SHIFT_CTRL_3	72
#define	IDM_KEY_SHIFT_CTRL_4	73
#define	IDM_KEY_SHIFT_CTRL_5	74
#define	IDM_KEY_SHIFT_CTRL_6	75
#define	IDM_KEY_SHIFT_CTRL_7	76
#define	IDM_KEY_SHIFT_CTRL_8	77
#define	IDM_KEY_SHIFT_CTRL_9	78
#define	IDM_KEY_SHIFT_CTRL_0	79
#define	IDM_KEY_A	80
#define	IDM_KEY_B	81
#define	IDM_KEY_C	82
#define	IDM_KEY_D	83
#define	IDM_KEY_E	84
#define	IDM_KEY_F	85
#define	IDM_KEY_G	86
#define	IDM_KEY_H	87
#define	IDM_KEY_I	88
#define	IDM_KEY_J	89
#define	IDM_KEY_K	90
#define	IDM_KEY_L	91
#define	IDM_KEY_M	92
#define	IDM_KEY_N	93
#define	IDM_KEY_O	94
#define	IDM_KEY_P	95
#define	IDM_KEY_Q	96
#define	IDM_KEY_R	97
#define	IDM_KEY_S	98
#define	IDM_KEY_T	99
#define	IDM_KEY_U	100
#define	IDM_KEY_V	101
#define	IDM_KEY_W	102
#define	IDM_KEY_X	103
#define	IDM_KEY_Y	104
#define	IDM_KEY_Z	105
#define	IDM_KEY_CTRL_A	106
#define	IDM_KEY_CTRL_B	107
#define	IDM_KEY_CTRL_C	108
#define	IDM_KEY_CTRL_D	109
#define	IDM_KEY_CTRL_E	110
#define	IDM_KEY_CTRL_F	111
#define	IDM_KEY_CTRL_G	112
#define	IDM_KEY_CTRL_H	113
#define	IDM_KEY_CTRL_I	114
#define	IDM_KEY_CTRL_J	115
#define	IDM_KEY_CTRL_K	116
#define	IDM_KEY_CTRL_L	117
#define	IDM_KEY_CTRL_M	118
#define	IDM_KEY_CTRL_N	119
#define	IDM_KEY_CTRL_O	120
#define	IDM_KEY_CTRL_P	121
#define	IDM_KEY_CTRL_Q	122
#define	IDM_KEY_CTRL_R	123
#define	IDM_KEY_CTRL_S	124
#define	IDM_KEY_CTRL_T	125
#define	IDM_KEY_CTRL_U	126
#define	IDM_KEY_CTRL_V	127
#define	IDM_KEY_CTRL_W	128
#define	IDM_KEY_CTRL_X	129
#define	IDM_KEY_CTRL_Y	130
#define	IDM_KEY_CTRL_Z	131
#define	IDM_KEY_SHIFT_A	132
#define	IDM_KEY_SHIFT_B	133
#define	IDM_KEY_SHIFT_C	134
#define	IDM_KEY_SHIFT_D	135
#define	IDM_KEY_SHIFT_E	136
#define	IDM_KEY_SHIFT_F	137
#define	IDM_KEY_SHIFT_G	138
#define	IDM_KEY_SHIFT_H	139
#define	IDM_KEY_SHIFT_I	140
#define	IDM_KEY_SHIFT_J	141
#define	IDM_KEY_SHIFT_K	142
#define	IDM_KEY_SHIFT_L	143
#define	IDM_KEY_SHIFT_M	144
#define	IDM_KEY_SHIFT_N	145
#define	IDM_KEY_SHIFT_O	146
#define	IDM_KEY_SHIFT_P	147
#define	IDM_KEY_SHIFT_Q	148
#define	IDM_KEY_SHIFT_R	149
#define	IDM_KEY_SHIFT_S	150
#define	IDM_KEY_SHIFT_T	151
#define	IDM_KEY_SHIFT_U	152
#define	IDM_KEY_SHIFT_V	153
#define	IDM_KEY_SHIFT_W	154
#define	IDM_KEY_SHIFT_X	155
#define	IDM_KEY_SHIFT_Y	156
#define	IDM_KEY_SHIFT_Z	157
#define	IDM_KEY_SHIFT_CTRL_A	158
#define	IDM_KEY_SHIFT_CTRL_B	159
#define	IDM_KEY_SHIFT_CTRL_C	160
#define	IDM_KEY_SHIFT_CTRL_D	161
#define	IDM_KEY_SHIFT_CTRL_E	162
#define	IDM_KEY_SHIFT_CTRL_F	163
#define	IDM_KEY_SHIFT_CTRL_G	164
#define	IDM_KEY_SHIFT_CTRL_H	165
#define	IDM_KEY_SHIFT_CTRL_I	166
#define	IDM_KEY_SHIFT_CTRL_J	167
#define	IDM_KEY_SHIFT_CTRL_K	168
#define	IDM_KEY_SHIFT_CTRL_L	169
#define	IDM_KEY_SHIFT_CTRL_M	170
#define	IDM_KEY_SHIFT_CTRL_N	171
#define	IDM_KEY_SHIFT_CTRL_O	172
#define	IDM_KEY_SHIFT_CTRL_P	173
#define	IDM_KEY_SHIFT_CTRL_Q	174
#define	IDM_KEY_SHIFT_CTRL_R	175
#define	IDM_KEY_SHIFT_CTRL_S	176
#define	IDM_KEY_SHIFT_CTRL_T	177
#define	IDM_KEY_SHIFT_CTRL_U	178
#define	IDM_KEY_SHIFT_CTRL_V	179
#define	IDM_KEY_SHIFT_CTRL_W	180
#define	IDM_KEY_SHIFT_CTRL_X	181
#define	IDM_KEY_SHIFT_CTRL_Y	182
#define	IDM_KEY_SHIFT_CTRL_Z	183


/////////////////////////////////////////////////////////////////////////////
#define	IDM_FILE	400
#define	IDM_FILE_CANCEL	401
#define	IDM_FILE_QUIT	402


/////////////////////////////////////////////////////////////////////////////
#define	IDM_VIEW	500
#define	IDM_VIEW_SHOW_NODE	501
#define	IDM_VIEW_SHOW_EDGE	502
#define	IDM_VIEW_SHOW_COMMUNITY	503
#define	IDM_VIEW_SHOW_COMMUNITY_EDGE	504

#define	IDM_VIEW_NODE_SIZE	506
#define	IDM_VIEW_NODE_SIZE_UPDATE	507
#define	IDM_VIEW_NODE_SIZE_CANCEL	508
#define	IDM_VIEW_NODE_SIZE_UNIFORM	509
#define	IDM_VIEW_NODE_SIZE_WEIGHT	510
#define	IDM_VIEW_NODE_SIZE_DEGREE_CENTRALITY	511
#define	IDM_VIEW_NODE_SIZE_CLOSENESS_CENTRALITY	512
#define	IDM_VIEW_NODE_SIZE_BETWEENNESS_CENTRALITY	513
#define	IDM_VIEW_NODE_SIZE_PAGERANK	514
#define	IDM_VIEW_NODE_SIZE_POINT	515

#define	IDM_VIEW_EDGE_WIDTH	517
#define	IDM_VIEW_EDGE_WIDTH_UPDATE	518
#define	IDM_VIEW_EDGE_WIDTH_CANCEL	519
#define	IDM_VIEW_EDGE_WIDTH_UNIFORM	520
#define	IDM_VIEW_EDGE_WIDTH_WEIGHT	521
#define	IDM_VIEW_EDGE_WIDTH_BETWEENNESS_CENTRALITY	522

#define	IDM_VIEW_NODE_STYLE	524
#define	IDM_VIEW_NODE_STYLE_POLYGON	525
#define	IDM_VIEW_NODE_STYLE_TEXTURE	526
#define	IDM_VIEW_EDGE_STYLE	527
#define	IDM_VIEW_EDGE_STYLE_LINE	528
#define	IDM_VIEW_EDGE_STYLE_POLYGON	529
#define	IDM_VIEW_COMMUNITY_STYLE	530
#define	IDM_VIEW_COMMUNITY_STYLE_POLYGON_CIRCLE	531
#define	IDM_VIEW_COMMUNITY_STYLE_TEXTURE	532
#define	IDM_VIEW_COMMUNITY_EDGE_STYLE	533
#define	IDM_VIEW_COMMUNITY_EDGE_STYLE_LINE	534
#define	IDM_VIEW_COMMUNITY_EDGE_STYLE_POLYGON	535


/////////////////////////////////////////////////////////////////////////////
#define	IDM_STRING	539
#define	IDM_STRING_SHOW_NODE_NAME	540
#define	IDM_STRING_SHOW_EDGE_NAME	541
#define	IDM_STRING_SHOW_COMMUNITY_NAME	542
#define	IDM_STRING_SHOW_COMMUNITY_EDGE_NAME	543
#define	IDM_STRING_NODE_NAME_SIZE	544
#define	IDM_STRING_NODE_NAME_SIZE_VARIABLE	545
#define	IDM_STRING_NODE_NAME_SIZE_0	546
#define	IDM_STRING_NODE_NAME_SIZE_1	547
#define	IDM_STRING_NODE_NAME_SIZE_2	548
#define	IDM_STRING_NODE_NAME_SIZE_3	549
#define	IDM_STRING_NODE_NAME_SIZE_4	550
#define	IDM_STRING_EDGE_NAME_SIZE	551
#define	IDM_STRING_EDGE_NAME_SIZE_VARIABLE	552
#define	IDM_STRING_EDGE_NAME_SIZE_0	553
#define	IDM_STRING_EDGE_NAME_SIZE_1	554
#define	IDM_STRING_EDGE_NAME_SIZE_2	555
#define	IDM_STRING_EDGE_NAME_SIZE_3	556
#define	IDM_STRING_EDGE_NAME_SIZE_4	557
#define	IDM_STRING_COMMUNITY_NAME_SIZE	558
#define	IDM_STRING_COMMUNITY_NAME_SIZE_VARIABLE	559
#define	IDM_STRING_COMMUNITY_NAME_SIZE_0	560
#define	IDM_STRING_COMMUNITY_NAME_SIZE_1	561
#define	IDM_STRING_COMMUNITY_NAME_SIZE_2	562
#define	IDM_STRING_COMMUNITY_NAME_SIZE_3	563
#define	IDM_STRING_COMMUNITY_NAME_SIZE_4	564
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE	565
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_VARIABLE	566
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_0	567
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_1	568
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_2	569
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_3	570
#define	IDM_STRING_COMMUNITY_EDGE_NAME_SIZE_4	571
#define	IDM_STRING_FONT_TYPE	572
#define	IDM_STRING_FONT_TYPE_POLYGON	573
#define	IDM_STRING_FONT_TYPE_TEXTURE	574
#define	IDM_STRING_SHOW_FPS	575
#define	IDM_STRING_SHOW_LAYER_NAME	576


/////////////////////////////////////////////////////////////////////////////
#define	IDM_EDIT	580
#define	IDM_EDIT_MARK_ON_CURRENT_LAYER	581
#define	IDM_EDIT_MARK_NODES_ON_CURRENT_LAYER	582
#define	IDM_EDIT_MARK_EDGES_ON_CURRENT_LAYER	583
#define	IDM_EDIT_MARK_COMMUNITIES_ON_CURRENT_LAYER	900
#define	IDM_EDIT_MARK_COMMUNITY_EDGES_ON_CURRENT_LAYER	901
#define	IDM_EDIT_MARK_NODES_INSIDE_COMMUNITY_ON_CURRENT_LAYER	584
#define	IDM_EDIT_MARK_EDGES_INSIDE_COMMUNITY_ON_CURRENT_LAYER	585
#define	IDM_EDIT_MARK_ELEMENTS_INSIDE_COMMUNITY_ON_CURRENT_LAYER	586
#define	IDM_EDIT_MARK_NODES_OUTSIDE_COMMUNITY_ON_CURRENT_LAYER	587
#define	IDM_EDIT_MARK_EDGES_OUTSIDE_COMMUNITY_ON_CURRENT_LAYER	588
#define	IDM_EDIT_MARK_ELEMENTS_OUTSIDE_COMMUNITY_ON_CURRENT_LAYER	589
#define	IDM_EDIT_MARK_ALL_ELEMENTS_ON_CURRENT_LAYER	590
#define	IDM_EDIT_INVERT_MARK_ON_CURRENT_LAYER	591

#define	IDM_EDIT_MARK_ON_EACH_LAYER	593
#define	IDM_EDIT_MARK_NODES_ON_EACH_LAYER	594
#define	IDM_EDIT_MARK_EDGES_ON_EACH_LAYER	595
#define	IDM_EDIT_MARK_COMMUNITIES_ON_EACH_LAYER	902
#define	IDM_EDIT_MARK_COMMUNITY_EDGES_ON_EACH_LAYER	903
#define	IDM_EDIT_MARK_NODES_INSIDE_COMMUNITY_ON_EACH_LAYER	596
#define	IDM_EDIT_MARK_EDGES_INSIDE_COMMUNITY_ON_EACH_LAYER	597
#define	IDM_EDIT_MARK_ELEMENTS_INSIDE_COMMUNITY_ON_EACH_LAYER	598
#define	IDM_EDIT_MARK_NODES_OUTSIDE_COMMUNITY_ON_EACH_LAYER	599
#define	IDM_EDIT_MARK_EDGES_OUTSIDE_COMMUNITY_ON_EACH_LAYER	600
#define	IDM_EDIT_MARK_ELEMENTS_OUTSIDE_COMMUNITY_ON_EACH_LAYER	601
#define	IDM_EDIT_MARK_ALL_ELEMENTS_ON_EACH_LAYER	602
#define	IDM_EDIT_INVERT_MARK_ON_EACH_LAYER	603

#define	IDM_EDIT_HIDE_MARKED_ELEMENTS	605
#define	IDM_EDIT_HIDE_MARKED_NODES_ON_CURRENT_LAYER	606
#define	IDM_EDIT_HIDE_MARKED_EDGES_ON_CURRENT_LAYER	607
#define	IDM_EDIT_HIDE_MARKED_ELEMENTS_ON_CURRENT_LAYER	608
#define	IDM_EDIT_HIDE_MARKED_NODES_ON_EACH_LAYER	609
#define	IDM_EDIT_HIDE_MARKED_EDGES_ON_EACH_LAYER	610
#define	IDM_EDIT_HIDE_MARKED_ELEMENTS_ON_EACH_LAYER	611

#define	IDM_EDIT_HIDE_MARKED_ELEMENTS_ALL	613
#define	IDM_EDIT_HIDE_MARKED_NODES_ON_CURRENT_LAYER_ALL	614
#define	IDM_EDIT_HIDE_MARKED_EDGES_ON_CURRENT_LAYER_ALL	615
#define	IDM_EDIT_HIDE_MARKED_ELEMENTS_ON_CURRENT_LAYER_ALL	616
#define	IDM_EDIT_HIDE_MARKED_NODES_ON_EACH_LAYER_ALL	617
#define	IDM_EDIT_HIDE_MARKED_EDGES_ON_EACH_LAYER_ALL	618
#define	IDM_EDIT_HIDE_MARKED_ELEMENTS_ON_EACH_LAYER_ALL	619

#define	IDM_EDIT_SHOW_HIDDEN_ELEMENTS	621
#define	IDM_EDIT_SHOW_HIDDEN_NODES_ON_CURRENT_LAYER	622
#define	IDM_EDIT_SHOW_HIDDEN_EDGES_ON_CURRENT_LAYER	623
#define	IDM_EDIT_SHOW_HIDDEN_ELEMENTS_ON_CURRENT_LAYER	624
#define	IDM_EDIT_SHOW_HIDDEN_NODES_ON_EACH_LAYER	625
#define	IDM_EDIT_SHOW_HIDDEN_EDGES_ON_EACH_LAYER	626
#define	IDM_EDIT_SHOW_HIDDEN_ELEMENTS_ON_EACH_LAYER	627

#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS	629
#define	IDM_EDIT_REMOVE_MARKED_NODES_ON_CURRENT_LAYER	630
#define	IDM_EDIT_REMOVE_MARKED_EDGES_ON_CURRENT_LAYER	631
#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS_ON_CURRENT_LAYER	632
#define	IDM_EDIT_REMOVE_MARKED_NODES_ON_EACH_LAYER	633
#define	IDM_EDIT_REMOVE_MARKED_EDGES_ON_EACH_LAYER	634
#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS_ON_EACH_LAYER	635

#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS_ALL	637
#define	IDM_EDIT_REMOVE_MARKED_NODES_ON_CURRENT_LAYER_ALL	638
#define	IDM_EDIT_REMOVE_MARKED_EDGES_ON_CURRENT_LAYER_ALL	639
#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS_ON_CURRENT_LAYER_ALL	640
#define	IDM_EDIT_REMOVE_MARKED_NODES_ON_EACH_LAYER_ALL	641
#define	IDM_EDIT_REMOVE_MARKED_EDGES_ON_EACH_LAYER_ALL	642
#define	IDM_EDIT_REMOVE_MARKED_ELEMENTS_ON_EACH_LAYER_ALL	643


/////////////////////////////////////////////////////////////////////////////
#define	IDM_LAYOUT	647
#define	IDM_LAYOUT_UPDATE	648
#define	IDM_LAYOUT_CANCEL	649
#define	IDM_LAYOUT_KAMADA_KAWAI_METHOD	650
#define	IDM_LAYOUT_HIGH_DIMENSIONAL_EMBEDDING	651
#define	IDM_LAYOUT_HIGH_DIMENSIONAL_EMBEDDING_1_2	652
#define	IDM_LAYOUT_HIGH_DIMENSIONAL_EMBEDDING_1_3	653
#define	IDM_LAYOUT_HIGH_DIMENSIONAL_EMBEDDING_2_3	654
#define	IDM_LAYOUT_CIRCLE	655
#define	IDM_LAYOUT_CIRCLE_IN_SIZE_ORDER	656
#define	IDM_LAYOUT_LATTICE	657
#define	IDM_LAYOUT_RANDOM	658
#define	IDM_LAYOUT_CARTOGRAMS	674
#define	IDM_LAYOUT_FORCE_DIRECTION	659
#define	IDM_LAYOUT_FORCE_DIRECTION_RUN	660
#define	IDM_LAYOUT_FORCE_DIRECTION_KAMADA_KAWAI_METHOD	661
#define	IDM_LAYOUT_FORCE_DIRECTION_KAMADA_KAWAI_METHOD_WITH_COMMUNITY_SEPARATION	662
#define	IDM_LAYOUT_FORCE_DIRECTION_COMMUNITY_ORIENTED	663
#define	IDM_LAYOUT_FORCE_DIRECTION_SPRING_AND_REPULSIVE_FORCE	664
#define	IDM_LAYOUT_FORCE_DIRECTION_LATTICE_GAS_METHOD	665
#define	IDM_LAYOUT_FORCE_DIRECTION_DESIGNTIDE	666
#define	IDM_LAYOUT_SHOW_LAYOUT_FRAME	667
#define	IDM_LAYOUT_INITIALIZE_LAYOUT_FRAME	668
#define	IDM_LAYOUT_SHOW_GRID	669
#define	IDM_LAYOUT_SHOW_CENTER	670
#define	IDM_LAYOUT_INITIALIZE_EYEPOINT	671
#define	IDM_LAYOUT_ZOOM_IN	672
#define	IDM_LAYOUT_ZOOM_OUT	673


/////////////////////////////////////////////////////////////////////////////
#define	IDM_COMMUNITY_DETECTION	677
#define	IDM_COMMUNITY_DETECTION_UPDATE	678
#define	IDM_COMMUNITY_DETECTION_CANCEL	679
#define	IDM_COMMUNITY_TRANSITION_DIAGRAM	680
#define	IDM_COMMUNITY_TRANSITION_DIAGRAM_SCOPE_WIDER	800
#define	IDM_COMMUNITY_TRANSITION_DIAGRAM_SCOPE_NARROWER	801
#define	IDM_COMMUNITY_DETECTION_CONNECTED_COMPONENTS	681
#define	IDM_COMMUNITY_DETECTION_WEAKLY_CONNECTED_COMPONENTS	682
#define	IDM_COMMUNITY_DETECTION_STRONGLY_CONNECTED_COMPONENTS	683
#define	IDM_COMMUNITY_DETECTION_MODULARITY_MAXIMIZATION	684
#define	IDM_COMMUNITY_DETECTION_MODULARITY_MAXIMIZATION_USING_GREEDY_METHOD	685
#define	IDM_COMMUNITY_DETECTION_MODULARITY_MAXIMIZATION_USING_TEO_METHOD	686
#define	IDM_COMMUNITY_DETECTION_USE_WEIGHTED_MODULARITY	687
#define	IDM_COMMUNITY_DETECTION_CLIQUE_PERCOLATION	688
#define	IDM_COMMUNITY_DETECTION_CLIQUE_PERCOLATION_3	689
#define	IDM_COMMUNITY_DETECTION_CLIQUE_PERCOLATION_4	690
#define	IDM_COMMUNITY_DETECTION_CLIQUE_PERCOLATION_5	691
#define	IDM_COMMUNITY_DETECTION_OTHERS	692
#define	IDM_COMMUNITY_DETECTION_BETWEENNESS_CENTRALITY_SEPARATION	693
#define	IDM_COMMUNITY_DETECTION_INFORMATION_FLOW_MAPPING	694
#define	IDM_COMMUNITY_DETECTION_CLEAR	695


/////////////////////////////////////////////////////////////////////////////
#define	IDM_TIMELINE	699
#define	IDM_TIMELINE_NEXT	700
#define	IDM_TIMELINE_PREV	701
#define	IDM_TIMELINE_AUTO_RUN	702
#define	IDM_TIMELINE_STOP	703
#define	IDM_TIMELINE_FORWARD_1	704
#define	IDM_TIMELINE_FORWARD_2	705
#define	IDM_TIMELINE_FORWARD_3	706
#define	IDM_TIMELINE_FORWARD_4	707
#define	IDM_TIMELINE_BACKWARD_1	708
#define	IDM_TIMELINE_BACKWARD_2	709
#define	IDM_TIMELINE_BACKWARD_3	710
#define	IDM_TIMELINE_BACKWARD_4	711
#define	IDM_TIMELINE_SHOW_SLIDER	712

#endif // INCLUDE_GUARD_SOCIARIUM_PROJECT_RESOURCE_H
